### ISSUE TITLE
bad minute error in crontab

### ISSUE THREAD

**Issue by oilervoss** [rafi0101/traefik-ssl-certificate-exporter#3]
I have tried some with CRON_TIME but I have get the error:
> starr-certsdumper-1  | 2022-09-17 17:46:19: Docker container has been started. You can find the log file at /var/log/cron.log
> starr-certsdumper-1  | "scheduler.txt":0: bad minute
> starr-certsdumper-1  | errors in crontab file, can't install.

Docker compose.yml 
```yml
services:
  certsdumper:
    image: rafi0101/traefik-ssl-certificate-exporter
    environment:
      - TZ=Canada/Eastern
      - ON_START=1
      - CRON_TIME='* * */2 * *'
      - CERT_OWNER_ID=0
      - CERT_GROUP_ID=1000
    volumes:
      - ./config/traefik/acme.json:/app/traefik/acme.json:ro
      - /etc/ssl/:/app/certs
    deploy:
      restart_policy:
        delay: 34h
```

I have tried with simple and double quotes. Without CRON_TIME set, it works like a breeze
